const cantadas = [
    "Seu pai trabalha com peixe? Porque você é um filezinho! 🐟",
    "Você é Google Maps? Porque me perdi em você! 🗺️",
    "Você é WiFi? Porque sinto uma conexão! 📶",
    "Você é astrônomo? Porque seus olhos são estrelas! ⭐",
    "Você é ladrão? Porque roubou meu coração! 💘",
    "Você é advogado? Porque me defende de ficar sozinho! ⚖️",
    "Você é médico? Porque meu coração acelera perto de você! 💓",
    "Você é fotógrafo? Porque fica na minha mente o tempo todo! 📸",
    "Você é açúcar? Porque adoça minha vida! 🍬",
    "Você é travesseiro? Porque só penso em você na cama! 😏",
    "Você é Netflix? Porque fico viciado em você! 🎬",
    "Você é chuva? Porque molha meu coração! 🌧️",
    "Você é café? Porque não consigo começar o dia sem você! ☕",
    "Você é guitarra? Porque quando toco em você, tudo vira música! 🎸",
    "Você é feriado? Porque é tudo que eu precisava! 🎉",
    "Você é dicionário? Porque me deu sentido! 📖",
    "Você é ímã? Porque me atrai de todo jeito! 🧲",
    "Você é arco-íris? Porque aparece depois das tempestades! 🌈",
    "Você é elevador? Porque me levanta o astral! 🛗",
    "Você é dentista? Porque me deixa sorrindo! 😁",
    "Você é alarme? Porque faz meu coração disparar! ⏰",
    "Você é pizzaiolo? Porque faz tudo ficar mais gostoso! 🍕",
    "Você é piscina? Porque quero me afogar em você! 🏊",
    "Você é sol? Porque ilumina meu dia! ☀️",
    "Você é espelho? Porque não consigo parar de te olhar! 🪞",
    "Você é música? Porque fica na minha cabeça o dia todo! 🎵",
    "Você é biblioteca? Porque tenho muito a aprender com você! 📚",
    "Você é chef? Porque tempera minha vida! 👨‍🍳",
    "Você é arquiteto? Porque construiu uma casa no meu coração! 🏠",
    "Você é piloto? Porque me faz voar! ✈️",
    "Você é pintor? Porque colore minha vida! 🎨",
    "Você é chocolateiro? Porque é irresistível! 🍫",
    "Você é jardineiro? Porque faz florescer algo em mim! 🌸",
    "Você é mágico? Porque sumiu com minha solidão! 🪄",
    "Você é jogador de basquete? Porque entrou direto no meu coração! 🏀",
    "Você é cozinheiro? Porque mexeu com meu estômago e coração! ❤️",
    "Você é afinador? Porque me deixa em harmonia! 🎶",
    "Você é terapeuta? Porque me faz bem só de estar por perto! 🛋️",
    "Você é designer? Porque é perfeito em tudo! ✏️",
    "Você é bombeiro? Porque apaga o fogo... mas acende outro! 🔥",
    "Você é professor? Porque me ensina o que é amor! 🍎",
    "Você é geógrafo? Porque me perco no seu mapa! 🗺️",
    "Você é programador? Porque hackeou meu coração! 💻",
    "Você é surfista? Porque me faz perder o equilíbrio! 🏄",
    "Você é veterinário? Porque cuida até do meu coração de cachorro! 🐕",
    "Você é florista? Porque me faz querer te dar flores! 💐",
    "Você é DJ? Porque coloca meu coração para bater! 🎧",
    "Você é nutricionista? Porque é tudo que eu precisava na dieta! 🥗",
    "Você é arquivista? Porque guardo tudo sobre você! 📁",
    "Você é engenheiro? Porque construiu pontes até meu coração! 🌉",
    "Você é chef de confeitaria? Porque é mais doce que qualquer sobremesa! 🎂",
    "Você é astrónomo? Porque é a estrela mais brilhante! ⭐",
    "Você é historiador? Porque quero fazer história com você! 📜",
    "Você é guia turístico? Porque me perco em você! 🧭",
    "Você é carteiro? Porque entregou meu coração! 📬",
    "Você é maestro? Porque rege meu coração! 🎼",
    "Você é mergulhador? Porque me afogo em seus olhos! 🤿",
    "Você é astrofísico? Porque gravita ao redor do meu coração! 🪐",
    "Você é farmacêutico? Porque é o remédio que precisava! 💊",
    "Você é meteorologista? Porque previu a tempestade no meu coração! 🌪️",
    "Você é alpinista? Porque me faz chegar ao topo! 🏔️",
    "Você é bibliotecário? Porque guardou meu coração com cuidado! 📚",
    "Você é sommelier? Porque fica melhor com o tempo! 🍷",
    "Você é ceramista? Porque moldou meu coração! 🏺",
    "Você é salva-vidas? Porque salvou meu dia! 🏊",
    "Você é luthier? Porque faz meu coração vibrar! 🎸",
    "Você é futebolista? Porque chutou meu coração para as redes! ⚽",
    "Você é escritor? Porque é o personagem principal da minha vida! 📝",
    "Você é cenógrafo? Porque transformou meu mundo! 🎭",
    "Você é geólogo? Porque encontrou pedras preciosas em mim! 💎",
    "Você é filósofo? Porque me faz pensar em você! 🤔",
    "Você é nadador? Porque mergulhei de cabeça em você! 🏊",
    "Você é escoteiro? Porque sempre me ajuda quando preciso! ⚜️",
    "Você é sommelier de café? Porque é intenso e irresistível! ☕",
    "Você é nutricionista esportivo? Porque é combustível para minha vida! 🏋️",
    "Você é arquiteto paisagista? Porque criou um jardim no meu coração! 🌿",
    "Você é produtor musical? Porque criou a trilha da minha vida! 🎵",
    "Você é glaciologista? Porque derretes minha resistência! 🧊",
    "Você é astrobiologista? Porque és vida em outro nível! 👽",
    "Você é criptógrafo? Porque decifrei que me apaixonei! 🔐",
    "Você é oceanógrafo? Porque mergulho sempre mais fundo em você! 🌊",
    "Você é vulcanólogo? Porque provoca erupções no meu coração! 🌋",
    "Você é curador de museu? Porque é uma obra de arte! 🖼️",
    "Você é sommelier de chocolate? Porque é delicioso em todos os sentidos! 🍫",
    "Você é cartógrafo? Porque mapeou meu coração! 🗺️",
    "Você é foguetista? Porque me mandou à lua! 🚀",
    "Você é relojoeiro? Porque fez o tempo parar! ⌚",
    "Você é calígrafo? Porque escreve lindo no meu coração! ✍️",
    "Você é enólogo? Porque fica melhor com o tempo! 🍇",
    "Você é herborista? Porque é natural e irresistível! 🌿",
    "Você é doceiro? Porque é o doce da minha vida! 🍭",
    "Você é ilusionista? Porque fez minha solidão desaparecer! 🪄",
    "Você é poeta? Porque inspira meus melhores versos! 📜",
    "Você é cineasta? Porque é o melhor filme da minha vida! 🎬",
    "Você é designer de joias? Porque é raro e precioso! 💍",
    "Você é sommelier de chá? Porque me aquece por dentro! 🍵",
    "Você é tradutor? Porque traduziu o que meu coração sentia! 💬",
    "Você é arquivista musical? Porque guardo cada momento com você! 🎶",
    "Você é engenheiro aeroespacial? Porque me levou às alturas! 🛸",
];

module.exports = {
    name: 'cantadas',
    async execute(client, msg, { chatId }) {
        try {
            const cantada = cantadas[Math.floor(Math.random() * cantadas.length)];
            await client.sendMessage(chatId, `💘 *CANTADA YUKON*\n━━━━━━━━━━━━━━━━━━━━━\n${cantada}\n━━━━━━━━━━━━━━━━━━━━━`);
        } catch (e) {
            console.error("❌ Erro no /cantadas:", e);
        }
    }
};