const curiosidades = [
    "O tubarão não tem ossos! Seu corpo é feito de cartilagem endurecida. 🦈",
    "As abelhas podem reconhecer rostos humanos! 🐝",
    "A língua azul de um okapi tem 45 cm de comprimento! 🦒",
    "Os polvos têm três corações e sangue azul! 🐙",
    "Uma formiga pode carregar 50 vezes seu próprio peso! 🐜",
    "Os golfinhos dormem com um olho aberto! 🐬",
    "O mel nunca estraga. Mel com 3000 anos ainda é comestível! 🍯",
    "Os flamingos são naturalmente brancos. A cor rosa vem da alimentação! 🦩",
    "Um caramujo pode dormir por 3 anos seguidos! 🐌",
    "Os polvos têm 9 cérebros (1 central + 1 em cada tentáculo)! 🐙",
    "A língua de uma baleia azul é tão grande quanto um elefante! 🐋",
    "Os coalas têm impressões digitais quase idênticas às humanas! 🐨",
    "Um grupo de corvos é chamado de 'assassinato' em inglês! 🐦‍⬛",
    "As borboletas provam a comida com os pés! 🦋",
    "Os elefantes são os únicos animais que não conseguem pular! 🐘",
    "A água quente congela mais rápido que a fria (Efeito Mpemba)! 🧊",
    "Existem mais estrelas no universo do que grãos de areia na Terra! ⭐",
    "Os humanos compartilham 60% do DNA com bananas! 🍌",
    "Um relâmpago é 5 vezes mais quente que a superfície do sol! ⚡",
    "O coração de um camarão fica na cabeça! 🦐",
    "Os gatos passam 70% da vida dormindo! 😺",
    "A Lua se afasta da Terra 3,8 cm por ano! 🌙",
    "Os polvos podem abrir potes com tampas! 🐙",
    "O nariz humano pode detectar mais de 1 trilhão de cheiros! 👃",
    "As vacas têm melhores amigos e ficam estressadas quando separadas! 🐄",
    "Um raio pode esquentar o ar ao redor a 30.000°C! ⚡",
    "Os caracóis têm milhares de dentes minúsculos! 🐌",
    "A velocidade da luz percorre 7,5 voltas na Terra por segundo! 💡",
    "Os polvos podem mudar de cor em 0,3 segundos! 🐙",
    "Um humano médio anda o equivalente a 3 voltas ao mundo em toda a vida! 👣",
    "As abelhas rainha vivem até 5 anos! 🐝",
    "O sangue de lagosta é azul, pois contém cobre em vez de ferro! 🦞",
    "Um leão pode dormir até 20 horas por dia! 🦁",
    "A Antártida é o maior deserto do mundo! 🏔️",
    "Os peixes-palhaço conseguem mudar de sexo ao longo da vida! 🐠",
    "O DNA humano tem 3 bilhões de pares de bases! 🧬",
    "Uma nuvem de tempestade pode pesar mais de 500 mil toneladas! ☁️",
    "Os polvos têm três corações: dois branquiais e um sistêmico! 🐙",
    "O som de um trovão viaja a 340 m/s! ⛈️",
    "Os cachorros conseguem detectar câncer pelo olfato! 🐕",
    "A banana é tecnicamente uma erva, não uma fruta! 🍌",
    "Um polvo tem mais neurônios nos tentáculos do que no cérebro! 🐙",
    "A Lua tem terremotos chamados de 'lunamotos'! 🌙",
    "Os golfinhos têm nomes uns para os outros! 🐬",
    "O mel é produzido a partir do néctar processado no estômago das abelhas! 🍯",
    "Existem mais bactérias no corpo humano do que células! 🦠",
    "Uma borboleta pode ver cores que os humanos não enxergam! 🦋",
    "Os polvos são daltônicos mas conseguem imitar cores perfeitamente! 🐙",
    "O coração de uma baleia azul bate apenas 2 vezes por minuto! 🐋",
    "Um dia em Vênus é mais longo que um ano em Vênus! 🪐",
    "Os elefantes são os únicos animais com 4 joelhos! 🐘",
    "A teia de aranha é mais forte que o aço do mesmo diâmetro! 🕷️",
    "Os polvos têm braços, não tentáculos (exceto os cefalópodes)! 🐙",
    "Uma formiga rainha pode viver até 30 anos! 🐜",
    "O grito de uma cabra pode ter sotaque regional! 🐐",
    "O nariz de um cão é único como a impressão digital humana! 🐕",
    "A língua de uma girafa mede cerca de 45 cm! 🦒",
    "Os golfinhos conseguem chamar uns aos outros pelo nome! 🐬",
    "O cérebro humano tem 86 bilhões de neurônios! 🧠",
    "Um piolho aguenta até 26 horas submerso em água! 🦠",
    "Os crocodilos não conseguem morder se a boca estiver fechada por uma fita! 🐊",
    "A pele de um hipopótamo produz um protetor solar natural! 🦛",
    "Um beija-flor bate as asas 80 vezes por segundo! 🐦",
    "Os ratos conseguem rir quando estão felizes! 🐀",
    "O olho humano pode distinguir cerca de 10 milhões de cores! 👁️",
    "As baleias cantam para se comunicar por centenas de quilômetros! 🐋",
    "Um avestruz corre mais rápido que um cavalo! 🦃",
    "Os polvos têm sangue azul porque usam hemocianina em vez de hemoglobina! 🐙",
    "A Terra tem mais de 8 milhões de espécies de seres vivos! 🌍",
    "Um elefante pode detectar água subterrânea a 19 km de distância! 🐘",
    "Os caracóis têm até 14.000 dentes! 🐌",
    "O coração de um beija-flor bate 1260 vezes por minuto! 🐦",
    "Um grupo de pandas é chamado de 'embarras'! 🐼",
    "Os peixes-cofre são venenosos! 🐡",
    "A Lua está se afastando da Terra há 4,5 bilhões de anos! 🌙",
    "Um caracol pode dormir de 3 a 3,5 anos! 🐌",
    "As formigas não dormem, apenas descansam em pequenos ciclos! 🐜",
    "O gato doméstico compartilha 95,6% do DNA com o tigre! 🐱",
    "Um grupo de flamingos é chamado de 'flamboyance'! 🦩",
    "Os humanos são os únicos animais que choram por emoção! 😢",
    "Uma abelha rainha pode botar até 2000 ovos por dia! 🐝",
    "Os polvos podem abrir potes de vidro! 🐙",
    "O DNA de todos os humanos vivos é 99,9% idêntico! 🧬",
    "Um vaga-lume pode usar sua luz para atrair presas! 🌟",
    "Os elefantes reconhecem a si mesmos no espelho! 🐘",
    "Um grupo de gatos é chamado de 'clowder'! 🐱",
    "O sangue de polvo é azul e circula em três corações! 🐙",
    "A aranha-pavão dança para conquistar sua parceira! 🕷️",
    "Um besouro pode sustentar 1141 vezes seu próprio peso! 🪲",
    "Os golfinhos ficam 'bêbados' comendo baiacus! 🐬",
    "Um grupo de corvos se chama 'assassinato'! 🐦‍⬛",
    "A formiga-fogo pode sobreviver a enchentes formando uma jangada! 🐜",
    "Um humano pisca cerca de 15-20 vezes por minuto! 👁️",
    "Os pandas selvagens ficam sozinhos 99% do tempo! 🐼",
    "A luz do sol leva 8 minutos para chegar à Terra! ☀️",
    "Os cavalos conseguem dormir em pé! 🐴",
    "Um polvo pode abrir uma garrafa de dentro para fora! 🐙",
    "Os polvos vivem apenas 1 a 2 anos! 🐙",
    "Um grupo de pinguins é chamado de 'waddle'! 🐧",
    "Os ratos são mais rápidos que humanos ao aprender novas tarefas! 🐀",
    "O mel nunca estraga pois é um antibiótico natural! 🍯",
];

module.exports = {
    name: 'curiosidades',
    aliases: ['curiosidade'],
    async execute(client, msg, { chatId }) {
        try {
            const curiosidade = curiosidades[Math.floor(Math.random() * curiosidades.length)];
            await client.sendMessage(chatId, `🔍 *CURIOSIDADE DO DIA — YUKON*\n━━━━━━━━━━━━━━━━━━━━━\n${curiosidade}\n━━━━━━━━━━━━━━━━━━━━━`);
        } catch (e) {
            console.error("❌ Erro no /curiosidades:", e);
        }
    }
};