const frases = [
    "Vai lá, você pode mais do que imagina! 💪",
    "Cada dia é uma nova chance de ser melhor! 🌅",
    "Não desista. O começo é sempre o mais difícil! 🚀",
    "Acredite em si mesmo e tudo será possível! ⭐",
    "Seu único limite é você mesmo! 🔥",
    "Grandes conquistas começam com pequenos passos! 👣",
    "Você é mais forte do que qualquer obstáculo! 💎",
    "O sucesso é a soma de pequenos esforços diários! 📈",
    "Errar faz parte. Desistir é a única derrota! 🏆",
    "Hoje é um bom dia para ser feliz! 😊",
    "Você tem a força que precisa dentro de você! 🌟",
    "Seja a mudança que você quer ver no mundo! 🌍",
    "Cada conquista começa com a decisão de tentar! ✨",
    "A persistência transforma sonhos em realidade! 💫",
    "Você chegou longe demais para desistir agora! 🛤️",
    "O fracasso é apenas o começo do sucesso! 🌱",
    "Sua história ainda não acabou. Continue! 📖",
    "Seja grato pelo que tem e lute pelo que quer! 🙏",
    "Cada dia sem sorrir é um dia perdido! 😁",
    "O melhor momento para agir é agora! ⏰",
    "Acredite no processo, os resultados virão! 🌻",
    "Você é capaz de coisas incríveis! 🦋",
    "Não espere a tempestade passar, aprenda a dançar na chuva! 🌧️",
    "A vida é 10% o que acontece com você e 90% como você reage! 💡",
    "Sonhe grande, trabalhe duro, seja humilde! 🏔️",
    "Cada obstáculo é uma oportunidade disfarçada! 🎁",
    "Você é o autor da sua própria história! ✍️",
    "Nenhum esforço é desperdiçado. Tudo te fortalece! 💪",
    "O sucesso não é o destino, é a jornada! 🛤️",
    "Confie no seu timing. Cada coisa tem seu momento! ⏳",
    "Seja paciente. Coisas boas levam tempo! 🌺",
    "Você está crescendo, mesmo quando não percebe! 🌿",
    "A coragem não é ausência de medo, é agir mesmo com medo! 🦁",
    "Cada dia é uma página em branco. Escreva algo incrível! 📝",
    "Você é mais resiliente do que pensa! 🔄",
    "Acredite no poder dos seus sonhos! 💭",
    "O mundo precisa do que só você tem a oferecer! 🌎",
    "Não compare sua jornada com a dos outros! 🛣️",
    "Você é suficiente exatamente como é! 💖",
    "Pequenos progressos ainda são progressos! 📊",
    "Sua atitude determina sua direção! 🧭",
    "Seja forte quando tudo pede que você desista! 🏋️",
    "Cada manhã é uma segunda chance! 🌄",
    "Você tem tudo que precisa para vencer! 🏅",
    "Não limite seus desafios, desafie seus limites! 🚀",
    "O sucesso começa com acreditar! 🌟",
    "Faça o que puder, com o que tem, onde está! 💫",
    "Você é uma obra de arte em construção! 🎨",
    "Levante, sacuda a poeira e dê a volta por cima! 🔄",
    "A vida premia quem não desiste! 🏆",
    "Você é extraordinário de formas que ainda vai descobrir! ✨",
    "O caminho para o sucesso está sempre em construção! 🏗️",
    "Cada experiência te torna mais sábio! 🦉",
    "Seja a luz que você quer ver no mundo! 💡",
    "Você foi feito para deixar uma marca! 🌟",
    "Transforme seus sonhos em metas e suas metas em realidade! 🎯",
    "A gratidão abre portas que o esforço sozinho não consegue! 🚪",
    "Você tem potencial ilimitado! 🌈",
    "A vida começa no fim da sua zona de conforto! 🌊",
    "Suas palavras e pensamentos moldam sua realidade! 💭",
    "Seja persistente como a água que molda a pedra! 💧",
    "Você não precisa de permissão para brilhar! ⭐",
    "O hoje que você constrói é o amanhã que você vai viver! 🏠",
    "Não tenha medo de recomeçar! 🌱",
    "Você foi colocado aqui para fazer a diferença! 🌍",
    "A força que você precisa já está dentro de você! 💎",
    "Cada conquista te aproxima do seu propósito! 🎯",
    "Seja mais forte que suas desculpas! 💪",
    "O único jeito de fazer um ótimo trabalho é amando o que faz! ❤️",
    "Você é capaz de superar qualquer adversidade! 🦅",
    "Não espere as condições perfeitas, comece agora! 🏃",
    "Sua determinação é maior que qualquer obstáculo! 🧱",
    "Acredite: o melhor ainda está por vir! 🌈",
    "Você tem um propósito único neste mundo! 🌟",
    "A jornada de mil milhas começa com um único passo! 👣",
    "Seja você mesmo, todos os outros já estão ocupados! 😄",
    "Você tem a capacidade de reinventar sua história! 📖",
    "Cada dia é uma oportunidade de crescer! 🌱",
    "O fracasso é apenas feedback disfarçado! 📊",
    "Você é mais do que suas circunstâncias! 🦋",
    "Confie no processo, o resultado virá! 🌻",
    "Seja protagonista da sua própria vida! 🎬",
    "Você tem tudo para vencer, acredite! 🏆",
    "Transforme a dor em combustível para o sucesso! 🔥",
    "A sua hora vai chegar, continue firme! ⏰",
    "Você nasceu para brilhar! ✨",
    "Cada desafio te torna mais forte! 💪",
    "Não pare quando estiver cansado, pare quando terminar! 🏁",
    "Você é uma força da natureza! 🌪️",
    "O esforço de hoje é o sucesso de amanhã! 📈",
    "Seja grato, seja forte, seja você! 🙏",
    "Você tem coragem de sobra para encarar qualquer situação! 🦁",
    "Não é sobre ser perfeito, é sobre ser autêntico! 💖",
    "Cada passo conta, não importa o tamanho! 👟",
    "Você é capaz de transformar sua vida! 🌟",
    "A persistência é o segredo dos grandes vencedores! 🥇",
    "Você tem tudo para ser incrível hoje! 🚀",
    "Não deixe que o medo te impeça de tentar! 🎯",
    "Você é mais valioso do que imagina! 💎",
];

module.exports = {
    name: 'frasemotivacional',
    aliases: ['motivacao', 'motivacional'],
    async execute(client, msg, { chatId }) {
        try {
            const frase = frases[Math.floor(Math.random() * frases.length)];
            await client.sendMessage(chatId, `🌟 *FRASE MOTIVACIONAL — YUKON*\n━━━━━━━━━━━━━━━━━━━━━\n"${frase}"\n━━━━━━━━━━━━━━━━━━━━━`);
        } catch (e) {
            console.error("❌ Erro no /frasemotivacional:", e);
        }
    }
};