const piadas = [
    "O que é um pontinho preto no avião? Uma aeromosca! ✈️🪰",
    "Por que o livro de matemática foi ao psicólogo? Porque tinha muitos problemas! 📚😂",
    "O que o zero disse para o oito? Bonito cinto! 🔢",
    "Por que o espantalho ganhou um prêmio? Porque ele era o melhor no seu campo! 🌾🏆",
    "O que é um elefante na neve? Um elefante frio! 🐘❄️",
    "Por que o computador foi ao médico? Porque estava com vírus! 💻🤧",
    "O que o oceano disse para a praia? Nada, só deu uma onda! 🌊",
    "Por que o peixe não faz amigos? Porque é muito reservado! 🐟",
    "O que é um pinto amarelo dentro de uma caixa preta? Um pinto de luto! 🐥",
    "Por que o vampiro parou de atacar? Porque estava com falta de calo! 🧛",
    "O que o Tarzan falou quando viu uma manada de elefantes? Nada, eles já sabiam! 🐘",
    "Por que a professora usou óculos escuros? Porque os alunos eram muito brilhantes! 🕶️",
    "O que o chocolate disse para a bala? Você quer sair com um cara durão? 🍫",
    "Por que o esqueleto não briga? Porque não tem estômago para isso! 💀",
    "O que é uma formiga na cabeça de uma criança? Uma tiara! 🐜",
    "Por que o milho foi ao dentista? Porque estava com dor de espiga! 🌽",
    "O que é um alho no espaço? Um disco voador! 🧄🛸",
    "Por que o tomate ficou vermelho? Porque viu a salada sem roupa! 🍅",
    "O que a impressora disse para o papel? Pode contar comigo! 🖨️",
    "Por que o gato caiu do telhado? Porque perdeu o miau-librio! 🐱",
    "O que é uma vaca com dois chifres? Bichovaca! 🐄",
    "Por que o fantasma não mente? Porque você pode ver através dele! 👻",
    "O que o garfo disse para a colher? Para de misturar as coisas! 🍴",
    "Por que a lua foi ao banco? Para pegar um empréstimo lunar! 🌙",
    "O que é um boomerang que não volta? Um graveto! 🪃",
    "Por que o relógio foi processado? Porque avançou demais! ⏰",
    "O que o pato disse para a pata? Vem me beijar, pato! 🦆",
    "Por que o leão é o rei da selva? Porque o rei da floresta estava ocupado! 🦁",
    "O que é um peixe sem olhos? Um pxe! 🐟",
    "Por que o padeiro é rico? Porque tem muita grana! 🍞💰",
    "O que o travesseiro disse para a cama? Você me apoia demais! 🛏️",
    "Por que a banana foi ao médico? Porque não estava se sentindo bem da casca! 🍌",
    "O que é um cego num saco de bolas? Uma bola a mais! ⚽",
    "Por que o livro foi ao banheiro? Porque estava passando por um capítulo difícil! 📖",
    "O que o fogão disse para a panela? Você me aquece! 🔥",
    "Por que a porta foi ao psicólogo? Porque vivia batendo cabeça! 🚪",
    "O que é um índio caído? Terra! 🏹",
    "Por que o fio elétrico foi ao dentista? Estava com corrente alternada! ⚡",
    "O que o espelho disse para o outro? Entre nós não tem segredo! 🪞",
    "Por que o avião não come? Porque já está cheio de passageiros! ✈️",
    "O que é um caracol no ombro? Um paraquedista atrasado! 🐌",
    "Por que o palco foi ao médico? Porque estava se sentindo em baixo! 🎭",
    "O que o lápis disse para o papel? Você me dá um ponto de apoio! ✏️",
    "Por que a girafa foi ao dentista? Para fazer canal no pescoço! 🦒",
    "O que é um peixe voando? Um aveixe! 🐟✈️",
    "Por que o sorvete chorou? Porque estava derretendo de amor! 🍦",
    "O que o táxi disse para o ônibus? Você para em todo lugar! 🚌",
    "Por que a borboleta foi ao psicólogo? Estava com fases demais! 🦋",
    "O que é um boi dormindo? Repouso bovino! 🐄",
    "Por que o bebê foi à escola? Para aprender a engatinhar nas matérias! 👶",
    "O que o sapato disse para o pé? Você me completa! 👟",
    "Por que o cachorro foi ao médico? Estava com muita lateria! 🐕",
    "O que é uma pedra caindo? Uma pedra indo ao chão! 🪨",
    "Por que a estrada foi ao banco? Para fazer uma curva de crédito! 🛣️",
    "O que o sol disse para a chuva? Para de me ofuscar! ☀️🌧️",
    "Por que o astronauta foi ao dentista? Para consertar o eclipse! 🚀",
    "O que é um grilo no ouvido? Uma consciência barulhenta! 🦗",
    "Por que a TV foi à academia? Para melhorar sua forma de transmissão! 📺",
    "O que o nariz disse para o olho? Você me fareja! 👃",
    "Por que a cadeira foi ao médico? Estava com dor no encosto! 🪑",
    "O que é um burro na neve? Um burro gelado! 🫏❄️",
    "Por que o canário não usa internet? Porque prefere o tuíte ao vivo! 🐦",
    "O que o chuveiro disse para a toalha? Para de me secar! 🚿",
    "Por que a mochila foi ao médico? Porque estava carregada de problemas! 🎒",
    "O que é um elétron triste? Um elétron com carga negativa! ⚛️",
    "Por que a planta foi ao psicólogo? Porque vivia se ramificando! 🌱",
    "O que o queijo disse para o vinho? Você me complementa! 🧀🍷",
    "Por que o celular foi à escola? Para melhorar sua rede de contatos! 📱",
    "O que é um peixe de óculos? Um peixe com visão aquática! 🐟👓",
    "Por que o travesseiro foi ao dentista? Porque sonhava com dor de dente! 😴",
    "O que o relógio disse para o despertador? Para de me acordar! ⏰",
    "Por que a maçã foi ao médico? Porque o médico sumiu! 🍎",
    "O que é um ninja sem roupa? Um homem pelado muito rápido! 🥷",
    "Por que a geladeira vai ao médico? Porque está sempre resfriada! 🧊",
    "O que o martelo disse para o prego? Você me acerta sempre! 🔨",
    "Por que o carro foi ao psicólogo? Porque estava engrenando mal! 🚗",
    "O que é um vulcão de bom humor? Uma erupção de alegria! 🌋",
    "Por que o coelho foi ao banco? Para guardar suas cenouras! 🐰🥕",
    "O que o garfo disse para a faca? Você corta onde eu não alcance! 🍴",
    "Por que a nuvem foi à academia? Para se manter em forma de chuva! ☁️",
    "O que é um pinguim no deserto? Um pinguim com muito calor! 🐧🏜️",
    "Por que o sapato chorou? Porque estava com o coração na sola! 👞",
    "O que o telescópio disse para o microscópio? Você vê o que eu não consigo! 🔭🔬",
    "Por que o ovo foi ao tribunal? Porque estava sendo frito! 🥚⚖️",
    "O que é uma cobra de pijama? Uma cobra com sono! 🐍😴",
    "Por que o balão foi à festa? Porque foi convidado! 🎈",
    "O que o alvo disse para a flecha? Você me acerta em cheio! 🎯",
    "Por que a janela foi ao médico? Porque estava sempre vidrada! 🪟",
    "O que é um astronauta com fome? Um astronauta comendo estrelas! 🚀⭐",
    "Por que o pão de queijo foi à academia? Para ficar sequinho! 🫓",
    "O que o mapa disse para o GPS? Você me substituiu, mas eu ainda tenho charme! 🗺️",
    "Por que a régua foi ao psicólogo? Porque não conseguia se medir! 📏",
    "O que é um fantasma surfando? Um fantasma pegando onda! 👻🏄",
    "Por que o dinossauro foi ao dentista? Porque estava extinto de dentes! 🦕",
    "O que o lixo disse para a lixeira? Finalmente um lar! 🗑️",
    "Por que a escada foi ao médico? Porque estava subindo demais! 🪜",
    "O que é um robô dançando? Uma máquina de funk! 🤖🎵",
    "Por que o biscoito foi ao médico? Porque estava se sentindo esfarelado! 🍪",
    "O que o pincel disse para a tela? Você me inspira! 🖌️",
];

module.exports = {
    name: 'humor',
    async execute(client, msg, { chatId }) {
        try {
            const piada = piadas[Math.floor(Math.random() * piadas.length)];
            await client.sendMessage(chatId, `😂 *HUMOR YUKON*\n━━━━━━━━━━━━━━━━━━━━━\n${piada}\n━━━━━━━━━━━━━━━━━━━━━`);
        } catch (e) {
            console.error("❌ Erro no /humor:", e);
        }
    }
};